---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for S3 Bucket'
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: comp4964-mho-lab9
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: Name of the newly created S3 bucket
    Value: !Ref MyS3Bucket